# Generated by Django 2.2.16 on 2022-04-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220403_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('moderator', 'moderator'), ('admin', 'admin'), ('sadmin', 'sadmin')], default='user', max_length=30),
        ),
    ]
